name: Deploy Auth Service

on:
  push:
    branches: [ cdk-4 ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.10'
    
    - name: Install dependencies and create wheel files
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        pip wheel -r requirements.txt -w ./src/wheels
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Upload to S3
      run: |
        aws s3 sync ./src/wheels s3://package-deployment-bucket-beta/wheelhouse/ 
        aws s3 cp requirements.txt s3://package-deployment-bucket-beta/ 
        aws s3 sync ./src s3://package-deployment-bucket-beta/src/ --exclude "wheels/*"    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Create .npmrc file
      run: |
        echo "@genflowly:registry=https://npm.pkg.github.com/" > .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> .npmrc
    
    - name: Install CDK
      run: npm install -g aws-cdk

    - name: Create .env file
      run: |
        cd cdk
        echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> .env
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
        echo "APP_ENV=BETA" >> .env

    - name: CDK Bootstrap
      run: |
        cd cdk
        cp ../.npmrc .
        npm ci
        npx cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ secrets.AWS_REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: CDK Deploy
      run: |
        cd cdk
        cp ../.npmrc .
        npm ci
        cdk deploy --require-approval never
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
